# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 700)
        MainWindow.setMinimumSize(QtCore.QSize(900, 0))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 700))
        self.centralwidget.setStyleSheet("*{\n"
"    border:none;\n"
"    \n"
"\n"
"    background-image: none;\n"
"\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setMinimumSize(QtCore.QSize(800, 700))
        self.main_body.setStyleSheet("")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_menu = QtWidgets.QFrame(self.main_body)
        self.left_menu.setMinimumSize(QtCore.QSize(50, 400))
        self.left_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_menu.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(92, 194, 178, 255), stop:1 rgba(34, 136, 169, 255));\n"
"\n"
"border:none;\n"
"")
        self.left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu.setObjectName("left_menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_menu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_toggle_burguer = QtWidgets.QPushButton(self.left_menu)
        self.btn_toggle_burguer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_toggle_burguer.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: none;\n"
"}\n"
"\n"
"\n"
"")
        self.btn_toggle_burguer.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons8-cardápio-50-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons8-excluir-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_toggle_burguer.setIcon(icon)
        self.btn_toggle_burguer.setIconSize(QtCore.QSize(50, 50))
        self.btn_toggle_burguer.setObjectName("btn_toggle_burguer")
        self.verticalLayout.addWidget(self.btn_toggle_burguer, 0, QtCore.Qt.AlignLeft)
        self.menu_burguer = QtWidgets.QFrame(self.left_menu)
        self.menu_burguer.setStyleSheet("border:none;\n"
"image:none;")
        self.menu_burguer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_burguer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_burguer.setObjectName("menu_burguer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu_burguer)
        self.verticalLayout_2.setContentsMargins(0, 0, 50, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_img_menu = QtWidgets.QFrame(self.menu_burguer)
        self.frame_img_menu.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_img_menu.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_img_menu.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_img_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_img_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_img_menu.setObjectName("frame_img_menu")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_img_menu)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menu_frame_icons = QtWidgets.QFrame(self.frame_img_menu)
        self.menu_frame_icons.setMinimumSize(QtCore.QSize(60, 60))
        self.menu_frame_icons.setMaximumSize(QtCore.QSize(60, 16777215))
        self.menu_frame_icons.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.menu_frame_icons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame_icons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame_icons.setObjectName("menu_frame_icons")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu_frame_icons)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.img_population = QtWidgets.QFrame(self.menu_frame_icons)
        self.img_population.setMinimumSize(QtCore.QSize(30, 30))
        self.img_population.setMaximumSize(QtCore.QSize(50, 50))
        self.img_population.setStyleSheet("image: url(:/icons/pessoas.png);\n"
"")
        self.img_population.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img_population.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img_population.setObjectName("img_population")
        self.verticalLayout_3.addWidget(self.img_population)
        self.img_gene = QtWidgets.QFrame(self.menu_frame_icons)
        self.img_gene.setMinimumSize(QtCore.QSize(30, 30))
        self.img_gene.setMaximumSize(QtCore.QSize(50, 50))
        self.img_gene.setStyleSheet("image: url(:/icons/icons8-atendimento-50.png);")
        self.img_gene.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img_gene.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img_gene.setObjectName("img_gene")
        self.verticalLayout_3.addWidget(self.img_gene)
        self.frame_9 = QtWidgets.QFrame(self.menu_frame_icons)
        self.frame_9.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_9.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_9.setStyleSheet("image: url(:/icons/icons8-seta-longa-acima-50.png);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_6 = QtWidgets.QFrame(self.menu_frame_icons)
        self.frame_6.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_6.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_6.setStyleSheet("image: url(:/icons/icons8-seta-longa-abaixo-50.png);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.menu_frame_icons)
        self.frame_5.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_5.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_5.setStyleSheet("image: url(:/icons/percentage-growth-50.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_8 = QtWidgets.QFrame(self.menu_frame_icons)
        self.frame_8.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_8.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_8.setStyleSheet("image: url(:/icons/pass-50.png);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.menu_frame_icons)
        self.frame_10.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_10.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_10.setStyleSheet("image: url(:/icons/grafico-de-porcentagem.png);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_7 = QtWidgets.QFrame(self.menu_frame_icons)
        self.frame_7.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_7.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_7.setStyleSheet("image: url(:/icons/slice-50.png);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout_3.addWidget(self.menu_frame_icons)
        self.menu_frame_labels = QtWidgets.QFrame(self.frame_img_menu)
        self.menu_frame_labels.setMaximumSize(QtCore.QSize(200, 16777215))
        self.menu_frame_labels.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.menu_frame_labels.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame_labels.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame_labels.setObjectName("menu_frame_labels")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu_frame_labels)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_total_population = QtWidgets.QLabel(self.menu_frame_labels)
        self.lbl_total_population.setStyleSheet("border: 1px solid black;")
        self.lbl_total_population.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_population.setObjectName("lbl_total_population")
        self.verticalLayout_4.addWidget(self.lbl_total_population)
        self.lbl_total_genes = QtWidgets.QLabel(self.menu_frame_labels)
        self.lbl_total_genes.setStyleSheet("border: 1px solid black;")
        self.lbl_total_genes.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_genes.setObjectName("lbl_total_genes")
        self.verticalLayout_4.addWidget(self.lbl_total_genes)
        self.lbl_max_gene = QtWidgets.QLabel(self.menu_frame_labels)
        self.lbl_max_gene.setStyleSheet("border: 1px solid black;")
        self.lbl_max_gene.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_max_gene.setObjectName("lbl_max_gene")
        self.verticalLayout_4.addWidget(self.lbl_max_gene)
        self.lbl_min_gene = QtWidgets.QLabel(self.menu_frame_labels)
        self.lbl_min_gene.setStyleSheet("border: 1px solid black;")
        self.lbl_min_gene.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_min_gene.setObjectName("lbl_min_gene")
        self.verticalLayout_4.addWidget(self.lbl_min_gene)
        self.lbl_target_percentage = QtWidgets.QLabel(self.menu_frame_labels)
        self.lbl_target_percentage.setStyleSheet("border: 1px solid black;")
        self.lbl_target_percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_target_percentage.setObjectName("lbl_target_percentage")
        self.verticalLayout_4.addWidget(self.lbl_target_percentage)
        self.lbl_min_succeeded = QtWidgets.QLabel(self.menu_frame_labels)
        self.lbl_min_succeeded.setStyleSheet("border: 1px solid black;")
        self.lbl_min_succeeded.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_min_succeeded.setObjectName("lbl_min_succeeded")
        self.verticalLayout_4.addWidget(self.lbl_min_succeeded)
        self.lbl_chosen_percentage = QtWidgets.QLabel(self.menu_frame_labels)
        self.lbl_chosen_percentage.setStyleSheet("border: 1px solid black;")
        self.lbl_chosen_percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_chosen_percentage.setObjectName("lbl_chosen_percentage")
        self.verticalLayout_4.addWidget(self.lbl_chosen_percentage)
        self.lbl_mutation_percentage = QtWidgets.QLabel(self.menu_frame_labels)
        self.lbl_mutation_percentage.setStyleSheet("border: 1px solid black;")
        self.lbl_mutation_percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mutation_percentage.setObjectName("lbl_mutation_percentage")
        self.verticalLayout_4.addWidget(self.lbl_mutation_percentage)
        self.horizontalLayout_3.addWidget(self.menu_frame_labels)
        self.menu_insert_info_burguer = QtWidgets.QFrame(self.frame_img_menu)
        self.menu_insert_info_burguer.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menu_insert_info_burguer.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.menu_insert_info_burguer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_insert_info_burguer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_insert_info_burguer.setObjectName("menu_insert_info_burguer")
        self.gridLayout = QtWidgets.QGridLayout(self.menu_insert_info_burguer)
        self.gridLayout.setContentsMargins(5, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.spinbox_population = QtWidgets.QSpinBox(self.menu_insert_info_burguer)
        self.spinbox_population.setMinimumSize(QtCore.QSize(30, 18))
        self.spinbox_population.setMaximumSize(QtCore.QSize(40, 18))
        self.spinbox_population.setStyleSheet("border: 1px solid black;")
        self.spinbox_population.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox_population.setMinimum(8)
        self.spinbox_population.setMaximum(5000)
        self.spinbox_population.setProperty("value", 50)
        self.spinbox_population.setObjectName("spinbox_population")
        self.gridLayout.addWidget(self.spinbox_population, 0, 0, 1, 1)
        self.spinbox_total_genes = QtWidgets.QSpinBox(self.menu_insert_info_burguer)
        self.spinbox_total_genes.setMinimumSize(QtCore.QSize(30, 18))
        self.spinbox_total_genes.setMaximumSize(QtCore.QSize(40, 18))
        self.spinbox_total_genes.setStyleSheet("border: 1px solid black;")
        self.spinbox_total_genes.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox_total_genes.setMinimum(1)
        self.spinbox_total_genes.setMaximum(5000)
        self.spinbox_total_genes.setProperty("value", 5)
        self.spinbox_total_genes.setObjectName("spinbox_total_genes")
        self.gridLayout.addWidget(self.spinbox_total_genes, 1, 0, 1, 1)
        self.spinbox_max_genes = QtWidgets.QSpinBox(self.menu_insert_info_burguer)
        self.spinbox_max_genes.setMinimumSize(QtCore.QSize(30, 18))
        self.spinbox_max_genes.setMaximumSize(QtCore.QSize(40, 18))
        self.spinbox_max_genes.setStyleSheet("border: 1px solid black;")
        self.spinbox_max_genes.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox_max_genes.setMinimum(1)
        self.spinbox_max_genes.setMaximum(5000)
        self.spinbox_max_genes.setProperty("value", 9)
        self.spinbox_max_genes.setObjectName("spinbox_max_genes")
        self.gridLayout.addWidget(self.spinbox_max_genes, 2, 0, 1, 1)
        self.spinbox_min_genes = QtWidgets.QSpinBox(self.menu_insert_info_burguer)
        self.spinbox_min_genes.setMinimumSize(QtCore.QSize(30, 18))
        self.spinbox_min_genes.setMaximumSize(QtCore.QSize(40, 18))
        self.spinbox_min_genes.setStyleSheet("border: 1px solid black;")
        self.spinbox_min_genes.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox_min_genes.setMinimum(1)
        self.spinbox_min_genes.setMaximum(5000)
        self.spinbox_min_genes.setProperty("value", 1)
        self.spinbox_min_genes.setObjectName("spinbox_min_genes")
        self.gridLayout.addWidget(self.spinbox_min_genes, 3, 0, 1, 1)
        self.spinbox_taget_percentage = QtWidgets.QSpinBox(self.menu_insert_info_burguer)
        self.spinbox_taget_percentage.setMinimumSize(QtCore.QSize(30, 18))
        self.spinbox_taget_percentage.setMaximumSize(QtCore.QSize(40, 18))
        self.spinbox_taget_percentage.setStyleSheet("border: 1px solid black;")
        self.spinbox_taget_percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox_taget_percentage.setMinimum(1)
        self.spinbox_taget_percentage.setMaximum(100)
        self.spinbox_taget_percentage.setProperty("value", 98)
        self.spinbox_taget_percentage.setObjectName("spinbox_taget_percentage")
        self.gridLayout.addWidget(self.spinbox_taget_percentage, 4, 0, 1, 1)
        self.spinbox_min_succeeded = QtWidgets.QSpinBox(self.menu_insert_info_burguer)
        self.spinbox_min_succeeded.setMinimumSize(QtCore.QSize(30, 18))
        self.spinbox_min_succeeded.setMaximumSize(QtCore.QSize(40, 18))
        self.spinbox_min_succeeded.setStyleSheet("border: 1px solid black;")
        self.spinbox_min_succeeded.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox_min_succeeded.setMinimum(1)
        self.spinbox_min_succeeded.setMaximum(5000)
        self.spinbox_min_succeeded.setProperty("value", 3)
        self.spinbox_min_succeeded.setObjectName("spinbox_min_succeeded")
        self.gridLayout.addWidget(self.spinbox_min_succeeded, 5, 0, 1, 1)
        self.spinbox_chosen_percentage = QtWidgets.QSpinBox(self.menu_insert_info_burguer)
        self.spinbox_chosen_percentage.setMinimumSize(QtCore.QSize(30, 18))
        self.spinbox_chosen_percentage.setMaximumSize(QtCore.QSize(40, 18))
        self.spinbox_chosen_percentage.setStyleSheet("border: 1px solid black;")
        self.spinbox_chosen_percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox_chosen_percentage.setMinimum(1)
        self.spinbox_chosen_percentage.setMaximum(100)
        self.spinbox_chosen_percentage.setProperty("value", 30)
        self.spinbox_chosen_percentage.setObjectName("spinbox_chosen_percentage")
        self.gridLayout.addWidget(self.spinbox_chosen_percentage, 6, 0, 1, 1)
        self.spinbox_mutation_percentage = QtWidgets.QSpinBox(self.menu_insert_info_burguer)
        self.spinbox_mutation_percentage.setMinimumSize(QtCore.QSize(30, 18))
        self.spinbox_mutation_percentage.setMaximumSize(QtCore.QSize(40, 18))
        self.spinbox_mutation_percentage.setStyleSheet("border: 1px solid black;")
        self.spinbox_mutation_percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox_mutation_percentage.setMaximum(100)
        self.spinbox_mutation_percentage.setProperty("value", 1)
        self.spinbox_mutation_percentage.setObjectName("spinbox_mutation_percentage")
        self.gridLayout.addWidget(self.spinbox_mutation_percentage, 7, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.menu_insert_info_burguer)
        self.verticalLayout_2.addWidget(self.frame_img_menu)
        self.frame_4 = QtWidgets.QFrame(self.menu_burguer)
        self.frame_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.menu_burguer)
        self.horizontalLayout_2.addWidget(self.left_menu)
        self.right_menu = QtWidgets.QFrame(self.main_body)
        self.right_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.right_menu.setStyleSheet("#right_menu{\n"
"    border-image: url(:/img_back/tec_background.jpeg);    \n"
"}")
        self.right_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_menu.setObjectName("right_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.right_menu)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.superior_info_frame = QtWidgets.QFrame(self.right_menu)
        self.superior_info_frame.setMinimumSize(QtCore.QSize(0, 100))
        self.superior_info_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.superior_info_frame.setStyleSheet("image:none;")
        self.superior_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.superior_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.superior_info_frame.setObjectName("superior_info_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.superior_info_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.center_superior_frame_csf = QtWidgets.QFrame(self.superior_info_frame)
        self.center_superior_frame_csf.setMinimumSize(QtCore.QSize(100, 50))
        self.center_superior_frame_csf.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.center_superior_frame_csf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.center_superior_frame_csf.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:4px solid  rgb(55, 162, 169);")
        self.center_superior_frame_csf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_superior_frame_csf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_superior_frame_csf.setObjectName("center_superior_frame_csf")
        self.horizontalLayout_4.addWidget(self.center_superior_frame_csf)
        self.right_superior_frame_rsf = QtWidgets.QFrame(self.superior_info_frame)
        self.right_superior_frame_rsf.setMinimumSize(QtCore.QSize(270, 50))
        self.right_superior_frame_rsf.setMaximumSize(QtCore.QSize(300, 16777215))
        self.right_superior_frame_rsf.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n"
"border:4px solid  rgb(55, 162, 169);")
        self.right_superior_frame_rsf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_superior_frame_rsf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_superior_frame_rsf.setObjectName("right_superior_frame_rsf")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.right_superior_frame_rsf)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.rsf_superior_frame = QtWidgets.QFrame(self.right_superior_frame_rsf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rsf_superior_frame.sizePolicy().hasHeightForWidth())
        self.rsf_superior_frame.setSizePolicy(sizePolicy)
        self.rsf_superior_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.rsf_superior_frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.rsf_superior_frame.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.rsf_superior_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rsf_superior_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rsf_superior_frame.setObjectName("rsf_superior_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.rsf_superior_frame)
        self.verticalLayout_9.setContentsMargins(3, -1, 3, 0)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.rsf_title = QtWidgets.QLabel(self.rsf_superior_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rsf_title.setFont(font)
        self.rsf_title.setStyleSheet("QLabel{\n"
"    color: rgb(0, 168, 240);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"}\n"
"QLabel:hover{\n"
"    color: rgb(51, 245, 242);\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.rsf_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rsf_title.setLineWidth(1)
        self.rsf_title.setMidLineWidth(0)
        self.rsf_title.setTextFormat(QtCore.Qt.AutoText)
        self.rsf_title.setScaledContents(False)
        self.rsf_title.setAlignment(QtCore.Qt.AlignCenter)
        self.rsf_title.setWordWrap(False)
        self.rsf_title.setIndent(-1)
        self.rsf_title.setObjectName("rsf_title")
        self.verticalLayout_9.addWidget(self.rsf_title)
        self.rsf_info = QtWidgets.QFrame(self.rsf_superior_frame)
        self.rsf_info.setMaximumSize(QtCore.QSize(16777215, 100))
        self.rsf_info.setStyleSheet("border:none;")
        self.rsf_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rsf_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rsf_info.setObjectName("rsf_info")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.rsf_info)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.conteiner_lbl_min = QtWidgets.QFrame(self.rsf_info)
        self.conteiner_lbl_min.setMaximumSize(QtCore.QSize(16777215, 100))
        self.conteiner_lbl_min.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.conteiner_lbl_min.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.conteiner_lbl_min.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conteiner_lbl_min.setObjectName("conteiner_lbl_min")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.conteiner_lbl_min)
        self.horizontalLayout_13.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbl_min_succeed = QtWidgets.QLabel(self.conteiner_lbl_min)
        self.lbl_min_succeed.setMinimumSize(QtCore.QSize(40, 0))
        self.lbl_min_succeed.setMaximumSize(QtCore.QSize(83, 16777215))
        self.lbl_min_succeed.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_min_succeed.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.lbl_min_succeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_min_succeed.setObjectName("lbl_min_succeed")
        self.horizontalLayout_13.addWidget(self.lbl_min_succeed)
        self.lbl_min_succeed_value = QtWidgets.QLabel(self.conteiner_lbl_min)
        self.lbl_min_succeed_value.setMinimumSize(QtCore.QSize(0, 35))
        self.lbl_min_succeed_value.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbl_min_succeed_value.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lbl_min_succeed_value.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(237, 131, 84);")
        self.lbl_min_succeed_value.setText("")
        self.lbl_min_succeed_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_min_succeed_value.setObjectName("lbl_min_succeed_value")
        self.horizontalLayout_13.addWidget(self.lbl_min_succeed_value)
        self.horizontalLayout_6.addWidget(self.conteiner_lbl_min)
        self.conteiner_lbl_perfect = QtWidgets.QFrame(self.rsf_info)
        self.conteiner_lbl_perfect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.conteiner_lbl_perfect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conteiner_lbl_perfect.setObjectName("conteiner_lbl_perfect")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.conteiner_lbl_perfect)
        self.horizontalLayout_14.setContentsMargins(7, 0, 15, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lbl_perfect_numb = QtWidgets.QLabel(self.conteiner_lbl_perfect)
        self.lbl_perfect_numb.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lbl_perfect_numb.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.lbl_perfect_numb.setObjectName("lbl_perfect_numb")
        self.horizontalLayout_14.addWidget(self.lbl_perfect_numb)
        self.lbl_perfect_value = QtWidgets.QLabel(self.conteiner_lbl_perfect)
        self.lbl_perfect_value.setMinimumSize(QtCore.QSize(0, 35))
        self.lbl_perfect_value.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbl_perfect_value.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(58, 183, 104);")
        self.lbl_perfect_value.setText("")
        self.lbl_perfect_value.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_perfect_value.setObjectName("lbl_perfect_value")
        self.horizontalLayout_14.addWidget(self.lbl_perfect_value)
        self.horizontalLayout_6.addWidget(self.conteiner_lbl_perfect)
        self.verticalLayout_9.addWidget(self.rsf_info)
        self.verticalLayout_8.addWidget(self.rsf_superior_frame)
        self.rsf_colocation_info = QtWidgets.QFrame(self.right_superior_frame_rsf)
        self.rsf_colocation_info.setMinimumSize(QtCore.QSize(0, 280))
        self.rsf_colocation_info.setMaximumSize(QtCore.QSize(16777215, 400))
        self.rsf_colocation_info.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.rsf_colocation_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rsf_colocation_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rsf_colocation_info.setObjectName("rsf_colocation_info")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.rsf_colocation_info)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rsf_info_position = QtWidgets.QFrame(self.rsf_colocation_info)
        self.rsf_info_position.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rsf_info_position.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.rsf_info_position.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rsf_info_position.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rsf_info_position.setObjectName("rsf_info_position")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.rsf_info_position)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.scrollArea = QtWidgets.QScrollArea(self.rsf_info_position)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 0px 0 0px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height:  10px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 0px;\n"
"    border-top-left-radius: 2px;\n"
"    border-top-right-radius: 2px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 0px;\n"
"    border-bottom-left-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"    \n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"       border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    height: 14px;\n"
"    margin: 0px 0 0px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(80, 80, 122);\n"
"    min-width:  30px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 0px;\n"
"    border-top-left-radius: 2px;\n"
"    border-top-right-radius: 2px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 0px;\n"
"    border-bottom-left-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    \n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal{\n"
"    background: none;\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal{\n"
"    background: none;\n"
"}\n"
"\n"
"")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 292, 300))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.rsf_info_scroll_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.rsf_info_scroll_frame.setMinimumSize(QtCore.QSize(130, 0))
        self.rsf_info_scroll_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rsf_info_scroll_frame.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.rsf_info_scroll_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rsf_info_scroll_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rsf_info_scroll_frame.setObjectName("rsf_info_scroll_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.rsf_info_scroll_frame)
        self.gridLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rsf_holder_first_place = QtWidgets.QFrame(self.rsf_info_scroll_frame)
        self.rsf_holder_first_place.setMinimumSize(QtCore.QSize(0, 0))
        self.rsf_holder_first_place.setMaximumSize(QtCore.QSize(16777215, 40))
        self.rsf_holder_first_place.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.rsf_holder_first_place.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rsf_holder_first_place.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rsf_holder_first_place.setObjectName("rsf_holder_first_place")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.rsf_holder_first_place)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_first_place_value = QtWidgets.QLabel(self.rsf_holder_first_place)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(130)
        sizePolicy.setHeightForWidth(self.lbl_first_place_value.sizePolicy().hasHeightForWidth())
        self.lbl_first_place_value.setSizePolicy(sizePolicy)
        self.lbl_first_place_value.setMinimumSize(QtCore.QSize(130, 40))
        self.lbl_first_place_value.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_first_place_value.setStyleSheet("border: 1px solid black;\n"
"border-radius: 18px; \n"
"background-color: rgba(255, 255, 255, 0);\n"
"")
        self.lbl_first_place_value.setText("")
        self.lbl_first_place_value.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_first_place_value.setObjectName("lbl_first_place_value")
        self.gridLayout_4.addWidget(self.lbl_first_place_value, 0, 2, 1, 1)
        self.icon_first_place = QtWidgets.QFrame(self.rsf_holder_first_place)
        self.icon_first_place.setMinimumSize(QtCore.QSize(40, 0))
        self.icon_first_place.setMaximumSize(QtCore.QSize(40, 16777215))
        self.icon_first_place.setStyleSheet("image: url(:/icons/fita-do-lugar.png);\n"
"")
        self.icon_first_place.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon_first_place.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon_first_place.setObjectName("icon_first_place")
        self.gridLayout_4.addWidget(self.icon_first_place, 0, 0, 1, 1)
        self.lbl_first_place_sum = QtWidgets.QLabel(self.rsf_holder_first_place)
        self.lbl_first_place_sum.setMinimumSize(QtCore.QSize(40, 0))
        self.lbl_first_place_sum.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lbl_first_place_sum.setStyleSheet("border-radius: 20px; \n"
"border: 1px solid black;")
        self.lbl_first_place_sum.setText("")
        self.lbl_first_place_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_first_place_sum.setObjectName("lbl_first_place_sum")
        self.gridLayout_4.addWidget(self.lbl_first_place_sum, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.rsf_holder_first_place, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.rsf_info_scroll_frame)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("QTableView {\n"
"    background-color: rgba(107, 117, 122,100);\n"
"}\n"
"QTableView::item{\n"
"       border: 1px solid black;\n"
"       border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    margin: 4; \n"
"}\n"
"")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tableWidget, 3, 0, 1, 1)
        self.rsf_holder_second_place = QtWidgets.QFrame(self.rsf_info_scroll_frame)
        self.rsf_holder_second_place.setMaximumSize(QtCore.QSize(16777215, 40))
        self.rsf_holder_second_place.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.rsf_holder_second_place.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rsf_holder_second_place.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rsf_holder_second_place.setObjectName("rsf_holder_second_place")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.rsf_holder_second_place)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.icon_second_place = QtWidgets.QFrame(self.rsf_holder_second_place)
        self.icon_second_place.setMinimumSize(QtCore.QSize(40, 0))
        self.icon_second_place.setMaximumSize(QtCore.QSize(40, 16777215))
        self.icon_second_place.setStyleSheet("image: url(:/icons/icons8-second-place-ribbon-50.png);\n"
"")
        self.icon_second_place.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon_second_place.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon_second_place.setObjectName("icon_second_place")
        self.gridLayout_5.addWidget(self.icon_second_place, 0, 0, 1, 1)
        self.lbl_second_place_value = QtWidgets.QLabel(self.rsf_holder_second_place)
        self.lbl_second_place_value.setMinimumSize(QtCore.QSize(130, 40))
        self.lbl_second_place_value.setStyleSheet("border: 1px solid black;\n"
"border-radius: 18px; \n"
"background-color: rgba(255, 255, 255, 0);\n"
"")
        self.lbl_second_place_value.setText("")
        self.lbl_second_place_value.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_second_place_value.setObjectName("lbl_second_place_value")
        self.gridLayout_5.addWidget(self.lbl_second_place_value, 0, 2, 1, 1)
        self.lbl_second_place_sum = QtWidgets.QLabel(self.rsf_holder_second_place)
        self.lbl_second_place_sum.setMinimumSize(QtCore.QSize(40, 0))
        self.lbl_second_place_sum.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lbl_second_place_sum.setStyleSheet("border-radius: 20px; \n"
"border: 1px solid black;")
        self.lbl_second_place_sum.setText("")
        self.lbl_second_place_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_second_place_sum.setObjectName("lbl_second_place_sum")
        self.gridLayout_5.addWidget(self.lbl_second_place_sum, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.rsf_holder_second_place, 1, 0, 1, 1)
        self.rsf_holder_third_place = QtWidgets.QFrame(self.rsf_info_scroll_frame)
        self.rsf_holder_third_place.setMaximumSize(QtCore.QSize(16777215, 40))
        self.rsf_holder_third_place.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.rsf_holder_third_place.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rsf_holder_third_place.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rsf_holder_third_place.setObjectName("rsf_holder_third_place")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.rsf_holder_third_place)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lbl_third_place_value = QtWidgets.QLabel(self.rsf_holder_third_place)
        self.lbl_third_place_value.setMinimumSize(QtCore.QSize(130, 40))
        self.lbl_third_place_value.setStyleSheet("border: 1px solid black;\n"
"border-radius: 18px; \n"
"background-color: rgba(255, 255, 255, 0);\n"
"")
        self.lbl_third_place_value.setText("")
        self.lbl_third_place_value.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_third_place_value.setObjectName("lbl_third_place_value")
        self.gridLayout_6.addWidget(self.lbl_third_place_value, 0, 2, 1, 1)
        self.icon_third_place = QtWidgets.QFrame(self.rsf_holder_third_place)
        self.icon_third_place.setMinimumSize(QtCore.QSize(40, 0))
        self.icon_third_place.setMaximumSize(QtCore.QSize(40, 16777215))
        self.icon_third_place.setStyleSheet("image: url(:/icons/icons8-third-place-ribbon-50.png);\n"
"border:none;")
        self.icon_third_place.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon_third_place.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon_third_place.setObjectName("icon_third_place")
        self.gridLayout_6.addWidget(self.icon_third_place, 0, 0, 1, 1)
        self.lbl_third_place_sum = QtWidgets.QLabel(self.rsf_holder_third_place)
        self.lbl_third_place_sum.setMinimumSize(QtCore.QSize(40, 0))
        self.lbl_third_place_sum.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lbl_third_place_sum.setStyleSheet("border-radius: 20px; \n"
"border: 1px solid black;")
        self.lbl_third_place_sum.setText("")
        self.lbl_third_place_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_third_place_sum.setObjectName("lbl_third_place_sum")
        self.gridLayout_6.addWidget(self.lbl_third_place_sum, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.rsf_holder_third_place, 2, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.rsf_info_scroll_frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea)
        self.horizontalLayout_7.addWidget(self.rsf_info_position)
        self.verticalLayout_8.addWidget(self.rsf_colocation_info)
        self.horizontalLayout_4.addWidget(self.right_superior_frame_rsf)
        self.verticalLayout_5.addWidget(self.superior_info_frame)
        self.inferior_info_frame = QtWidgets.QFrame(self.right_menu)
        self.inferior_info_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.inferior_info_frame.setMaximumSize(QtCore.QSize(16777215, 300))
        self.inferior_info_frame.setStyleSheet("image:none;")
        self.inferior_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inferior_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inferior_info_frame.setObjectName("inferior_info_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.inferior_info_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_inferior_frame_lif = QtWidgets.QFrame(self.inferior_info_frame)
        self.left_inferior_frame_lif.setMinimumSize(QtCore.QSize(50, 50))
        self.left_inferior_frame_lif.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.left_inferior_frame_lif.setStyleSheet("background-color: rgba(255, 255,255,0);\n"
"")
        self.left_inferior_frame_lif.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_inferior_frame_lif.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_inferior_frame_lif.setObjectName("left_inferior_frame_lif")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.left_inferior_frame_lif)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lif_container_lbl_frame = QtWidgets.QFrame(self.left_inferior_frame_lif)
        self.lif_container_lbl_frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lif_container_lbl_frame.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"border:none;")
        self.lif_container_lbl_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lif_container_lbl_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lif_container_lbl_frame.setObjectName("lif_container_lbl_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.lif_container_lbl_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lif_holder_lbl_container = QtWidgets.QFrame(self.lif_container_lbl_frame)
        self.lif_holder_lbl_container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lif_holder_lbl_container.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"border:4px solid  rgb(55, 162, 169);")
        self.lif_holder_lbl_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lif_holder_lbl_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lif_holder_lbl_container.setObjectName("lif_holder_lbl_container")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.lif_holder_lbl_container)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 110)
        self.gridLayout_2.setHorizontalSpacing(1)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_muts_name = QtWidgets.QLabel(self.lif_holder_lbl_container)
        self.lbl_muts_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_muts_name.setStyleSheet("color: rgb(0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lbl_muts_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_muts_name.setObjectName("lbl_muts_name")
        self.gridLayout_2.addWidget(self.lbl_muts_name, 1, 0, 1, 1)
        self.lbl_gens_name = QtWidgets.QLabel(self.lif_holder_lbl_container)
        self.lbl_gens_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_gens_name.setStyleSheet("color: rgb(0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.lbl_gens_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_gens_name.setObjectName("lbl_gens_name")
        self.gridLayout_2.addWidget(self.lbl_gens_name, 0, 0, 1, 1)
        self.lbl_elapsed_time_name = QtWidgets.QLabel(self.lif_holder_lbl_container)
        self.lbl_elapsed_time_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_elapsed_time_name.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.lbl_elapsed_time_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_elapsed_time_name.setObjectName("lbl_elapsed_time_name")
        self.gridLayout_2.addWidget(self.lbl_elapsed_time_name, 4, 0, 1, 1)
        self.lbl_worst_score_value = QtWidgets.QLabel(self.lif_holder_lbl_container)
        self.lbl_worst_score_value.setStyleSheet("QLabel{\n"
"    color: rgb(54, 160, 167);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border: none\n"
"}")
        self.lbl_worst_score_value.setObjectName("lbl_worst_score_value")
        self.gridLayout_2.addWidget(self.lbl_worst_score_value, 3, 1, 1, 1)
        self.lbl_best_score_name = QtWidgets.QLabel(self.lif_holder_lbl_container)
        self.lbl_best_score_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_best_score_name.setStyleSheet("border:none;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lbl_best_score_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_best_score_name.setObjectName("lbl_best_score_name")
        self.gridLayout_2.addWidget(self.lbl_best_score_name, 2, 0, 1, 1)
        self.lbl_gens_value = QtWidgets.QLabel(self.lif_holder_lbl_container)
        self.lbl_gens_value.setStyleSheet("QLabel{\n"
"    color: rgb(54, 160, 167);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border: none\n"
"}")
        self.lbl_gens_value.setObjectName("lbl_gens_value")
        self.gridLayout_2.addWidget(self.lbl_gens_value, 0, 1, 1, 1)
        self.lbl_elapsed_time_value = QtWidgets.QLabel(self.lif_holder_lbl_container)
        self.lbl_elapsed_time_value.setStyleSheet("QLabel{\n"
"    color: rgb(54, 160, 167);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border: none\n"
"}")
        self.lbl_elapsed_time_value.setObjectName("lbl_elapsed_time_value")
        self.gridLayout_2.addWidget(self.lbl_elapsed_time_value, 4, 1, 1, 1)
        self.lbl_muts_value = QtWidgets.QLabel(self.lif_holder_lbl_container)
        self.lbl_muts_value.setStyleSheet("QLabel{\n"
"    color: rgb(54, 160, 167);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border: none\n"
"}")
        self.lbl_muts_value.setObjectName("lbl_muts_value")
        self.gridLayout_2.addWidget(self.lbl_muts_value, 1, 1, 1, 1)
        self.lbl_worst_score_name = QtWidgets.QLabel(self.lif_holder_lbl_container)
        self.lbl_worst_score_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_worst_score_name.setStyleSheet("border:none;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lbl_worst_score_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_worst_score_name.setObjectName("lbl_worst_score_name")
        self.gridLayout_2.addWidget(self.lbl_worst_score_name, 3, 0, 1, 1)
        self.lbl_best_score_value = QtWidgets.QLabel(self.lif_holder_lbl_container)
        self.lbl_best_score_value.setStyleSheet("QLabel{\n"
"    color: rgb(54, 160, 167);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border: none\n"
"}")
        self.lbl_best_score_value.setObjectName("lbl_best_score_value")
        self.gridLayout_2.addWidget(self.lbl_best_score_value, 2, 1, 1, 1)
        self.horizontalLayout_9.addWidget(self.lif_holder_lbl_container)
        self.horizontalLayout_8.addWidget(self.lif_container_lbl_frame)
        self.lif_left_frame = QtWidgets.QFrame(self.left_inferior_frame_lif)
        self.lif_left_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lif_left_frame.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"border:4px solid  rgb(55, 162, 169);")
        self.lif_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lif_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lif_left_frame.setObjectName("lif_left_frame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.lif_left_frame)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_8.addWidget(self.lif_left_frame)
        self.horizontalLayout_5.addWidget(self.left_inferior_frame_lif)
        self.right_inferior_frame_rif = QtWidgets.QFrame(self.inferior_info_frame)
        self.right_inferior_frame_rif.setMinimumSize(QtCore.QSize(50, 50))
        self.right_inferior_frame_rif.setMaximumSize(QtCore.QSize(300, 16777215))
        self.right_inferior_frame_rif.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.right_inferior_frame_rif.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_inferior_frame_rif.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_inferior_frame_rif.setObjectName("right_inferior_frame_rif")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.right_inferior_frame_rif)
        self.verticalLayout_7.setContentsMargins(12, 0, 12, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rif_superior_frame = QtWidgets.QFrame(self.right_inferior_frame_rif)
        self.rif_superior_frame.setWhatsThis("")
        self.rif_superior_frame.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.rif_superior_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rif_superior_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rif_superior_frame.setObjectName("rif_superior_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.rif_superior_frame)
        self.verticalLayout_10.setContentsMargins(0, 3, 0, 60)
        self.verticalLayout_10.setSpacing(25)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_start_restart = QtWidgets.QPushButton(self.rif_superior_frame)
        self.btn_start_restart.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_start_restart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_start_restart.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(194, 255, 209);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(161, 255, 195);\n"
"    color: rgb(10, 153, 73);\n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid  rgb(97, 184, 133);\n"
"    border-radius: 35px;\n"
"}\n"
"")
        self.btn_start_restart.setObjectName("btn_start_restart")
        self.verticalLayout_10.addWidget(self.btn_start_restart)
        self.btn_cancel = QtWidgets.QPushButton(self.rif_superior_frame)
        self.btn_cancel.setEnabled(False)
        self.btn_cancel.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 194, 176);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(254, 175, 159);\n"
"    border: 2px solid rgb(208, 93, 93);\n"
"    color:;\n"
"    color: rgb(186, 54, 54);\n"
"    border-radius: 35px;\n"
"    font: 75 22pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:disabled{    \n"
"    background-color: rgb(200,200, 200);\n"
"    color: rgb(108, 108, 108);\n"
"    border-color: rgb(122, 122, 122);\n"
"\n"
"}\n"
"")
        self.btn_cancel.setObjectName("btn_cancel")
        self.verticalLayout_10.addWidget(self.btn_cancel)
        self.btn_view_graph = QtWidgets.QPushButton(self.rif_superior_frame)
        self.btn_view_graph.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_view_graph.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_view_graph.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(192, 219, 222);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(157, 223, 222);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid  rgb(67, 178, 176);\n"
"    color: rgb(31, 115, 127);\n"
"    border-radius: 35px;\n"
"    font: 75 22pt \"MS Shell Dlg 2\";\n"
"}\n"
"")
        self.btn_view_graph.setObjectName("btn_view_graph")
        self.verticalLayout_10.addWidget(self.btn_view_graph)
        self.btn_cancel.raise_()
        self.btn_view_graph.raise_()
        self.btn_start_restart.raise_()
        self.verticalLayout_7.addWidget(self.rif_superior_frame)
        self.horizontalLayout_5.addWidget(self.right_inferior_frame_rif)
        self.verticalLayout_5.addWidget(self.inferior_info_frame)
        self.horizontalLayout_2.addWidget(self.right_menu)
        self.horizontalLayout.addWidget(self.main_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_total_population.setText(_translate("MainWindow", "Total Population"))
        self.lbl_total_genes.setText(_translate("MainWindow", "Total Genes"))
        self.lbl_max_gene.setText(_translate("MainWindow", "Maximum Gene"))
        self.lbl_min_gene.setText(_translate("MainWindow", "Minimum Gene"))
        self.lbl_target_percentage.setText(_translate("MainWindow", "Target Percentage"))
        self.lbl_min_succeeded.setText(_translate("MainWindow", "Minimum Succeeded"))
        self.lbl_chosen_percentage.setText(_translate("MainWindow", "Chosen Percentage"))
        self.lbl_mutation_percentage.setText(_translate("MainWindow", "Mutation Percentage"))
        self.rsf_title.setText(_translate("MainWindow", "Succeeded"))
        self.lbl_min_succeed.setText(_translate("MainWindow", "Min Value:"))
        self.lbl_perfect_numb.setText(_translate("MainWindow", "Perfect:"))
        self.tableWidget.setSortingEnabled(False)
        self.lbl_muts_name.setText(_translate("MainWindow", "Mutations:"))
        self.lbl_gens_name.setText(_translate("MainWindow", "Generetions:"))
        self.lbl_elapsed_time_name.setText(_translate("MainWindow", "Elapsed Time:"))
        self.lbl_worst_score_value.setText(_translate("MainWindow", "0"))
        self.lbl_best_score_name.setText(_translate("MainWindow", "Best Score:"))
        self.lbl_gens_value.setText(_translate("MainWindow", "0"))
        self.lbl_elapsed_time_value.setText(_translate("MainWindow", "0"))
        self.lbl_muts_value.setText(_translate("MainWindow", "0"))
        self.lbl_worst_score_name.setText(_translate("MainWindow", "Worst Score:"))
        self.lbl_best_score_value.setText(_translate("MainWindow", "0"))
        self.btn_start_restart.setText(_translate("MainWindow", "START"))
        self.btn_cancel.setText(_translate("MainWindow", "CANCEL PROCESS"))
        self.btn_view_graph.setText(_translate("MainWindow", "VIEW GRAPH"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
